/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_final_;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Anubhav
 */
public class SignUpFinal extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public String mobileno=null;

    /**
     * Creates new form NewJFrame
     */
    public ImageIcon ResizeImage2(String imagePath, byte[]pic){
        ImageIcon myImage=null;
        if(imagePath!=null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lbl_image2.getWidth(), lbl_image2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    public ImageIcon ResizeImage3(String imagePath, byte[]pic){
        ImageIcon myImage=null;
        if(imagePath!=null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lbl_image3.getWidth(), lbl_image3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    String ImgPath="C:\\Users\\anubh\\Desktop\\DeskTop Icons\\Java Project Pics\\8.jpg";
    public SignUpFinal() {
        setTitle("ONLINE CHARITY SYSTEM - SIGNUP & LOGIN");
        initComponents();
        lbl_image2.setIcon(ResizeImage2(ImgPath,null));
        ImgPath="C:\\Users\\anubh\\Desktop\\DeskTop Icons\\Java Project Pics\\7.png";
        lbl_image3.setIcon(ResizeImage3(ImgPath,null));
        conn=JavaConnection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_f1 = new javax.swing.JTextField();
        txt_f2 = new javax.swing.JTextField();
        txt_f3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_f4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_f5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_f6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txt_f7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_f8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_f9 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        lbl_image3 = new javax.swing.JLabel();
        lbl_image2 = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(580, 250));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mobile Number:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(20, 150, 144, 22);

        txt_f1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f1);
        txt_f1.setBounds(170, 150, 236, 28);

        txt_f2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_f2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_f2);
        txt_f2.setBounds(170, 180, 236, 28);

        txt_f3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f3);
        txt_f3.setBounds(170, 220, 236, 28);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Address:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 250, 78, 22);

        txt_f4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f4);
        txt_f4.setBounds(170, 250, 236, 28);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Adhaar No.:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 290, 108, 22);

        txt_f5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f5);
        txt_f5.setBounds(170, 290, 236, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Full Name:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(70, 320, 97, 22);

        txt_f6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f6);
        txt_f6.setBounds(170, 320, 236, 28);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(90, 360, 73, 22);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(170, 360, 236, 28);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("EMail-ID:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(80, 400, 86, 22);

        txt_f7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f7);
        txt_f7.setBounds(170, 390, 236, 28);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("Register");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 430, 210, 37);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(253, 430, 150, 37);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(430, 93, 25, 370);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(70, 180, 94, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("City:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(130, 230, 41, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setText("SIGN-UP");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(190, 80, 162, 44);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("SIGN-IN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 80, 156, 44);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Mobile Number:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(450, 200, 144, 22);

        txt_f8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f8);
        txt_f8.setBounds(600, 200, 209, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Password:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(500, 250, 94, 22);

        txt_f9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txt_f9);
        txt_f9.setBounds(600, 250, 209, 28);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("Login");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(600, 290, 210, 37);
        getContentPane().add(lbl_image3);
        lbl_image3.setBounds(230, 10, 440, 70);
        getContentPane().add(lbl_image2);
        lbl_image2.setBounds(0, 0, 870, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_f2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_f2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txt_f1.setText("");
            txt_f2.setText("");
            txt_f3.setText("");
            txt_f4.setText("");
            txt_f5.setText("");
            txt_f6.setText("");
            txt_f7.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql = "insert into signup(mobile, password, city, address, adhaar, name, gender, email) values(?, ?, ?, ?, ?, ?, ?, ?)";
        try{
            pst=conn.prepareStatement(sql);
            String ab=txt_f1.getText();
            char a[]=ab.toCharArray();
            int count=0;
            for(int i=0;i<a.length;i++){
                if(Character.isDigit(a[i])){
                    count++;
                }
            }
            if(count==10){
                pst.setString(1, txt_f1.getText());
                pst.setString(2, txt_f2.getText());
                pst.setString(3, txt_f3.getText());
                pst.setString(4, txt_f4.getText());
                String a2=txt_f5.getText();
                char b[]=a2.toCharArray();
                int test1=0;
                for(int i=0;i<b.length;i++){
                    if(Character.isDigit(b[i])){
                        continue;
                    }
                    else{
                        test1=1;
                    }
                }
                if(test1==0){
                    pst.setString(5, txt_f5.getText());
                pst.setString(6, txt_f6.getText());
                pst.setString(7, jComboBox2.getSelectedItem().toString());
                pst.setString(8, txt_f7.getText());
                }
                else{
                    JOptionPane.showMessageDialog(null, "Enter a valid Adhaar Number.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter a valid 10 digit number.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            System.out.println("Registered");
            pst.execute();
            txt_f1.setText("");
            txt_f2.setText("");
            txt_f3.setText("");
            txt_f4.setText("");
            txt_f5.setText("");
            txt_f6.setText("");
            txt_f7.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String sql ="Select * from signup where mobile = ? and password = ?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_f8.getText());
            pst.setString(2, txt_f9.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                close();
                WelcomeFinal w=new WelcomeFinal();
                w.setVisible(true);
                System.out.println("Logged in successfully.");
            }else{
                JOptionPane.showMessageDialog(null, "ID and Password does not match.\nPress \"OK\" and try again.", "Wrong Input", JOptionPane.ERROR_MESSAGE);
                txt_f8.setText("");
                txt_f9.setText("");
                System.out.println("ID and Password does not match.");
            }
            pst.execute();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFinal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lbl_image2;
    private javax.swing.JLabel lbl_image3;
    private javax.swing.JTextField txt_f1;
    private javax.swing.JTextField txt_f2;
    private javax.swing.JTextField txt_f3;
    private javax.swing.JTextField txt_f4;
    private javax.swing.JTextField txt_f5;
    private javax.swing.JTextField txt_f6;
    private javax.swing.JTextField txt_f7;
    private javax.swing.JTextField txt_f8;
    private javax.swing.JPasswordField txt_f9;
    // End of variables declaration//GEN-END:variables
    private void close(){
        WindowEvent wc=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wc);
    }
}
