/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_final_;
import java.awt.*;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Anubhav
 */
public class WelcomeFinal extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public ImageIcon ResizeImage2(String imagePath, byte[]pic){
        ImageIcon myImage=null;
        if(imagePath!=null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lbl_image2.getWidth(), lbl_image2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    public ImageIcon ResizeImage3(String imagePath, byte[]pic){
        ImageIcon myImage=null;
        if(imagePath!=null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lbl_image3.getWidth(), lbl_image3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    public ImageIcon ResizeImage4(String imagePath, byte[]pic){
        ImageIcon myImage=null;
        if(imagePath!=null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lbl_image4.getWidth(), lbl_image4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    public ImageIcon ResizeImage5(String imagePath, byte[]pic){
        ImageIcon myImage=null;
        if(imagePath!=null){
            myImage = new ImageIcon(imagePath);
        }else{
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lbl_image5.getWidth(), lbl_image5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    String ImgPath="C:\\Users\\anubh\\Desktop\\DeskTop Icons\\Java Project Pics\\17.jpg";
    public WelcomeFinal() {
        setTitle("HOMEPAGE");
        initComponents();
        lbl_image2.setIcon(ResizeImage2(ImgPath,null));
        ImgPath="C:\\Users\\anubh\\Desktop\\DeskTop Icons\\Java Project Pics\\3.png";
        lbl_image3.setIcon(ResizeImage3(ImgPath,null));
        ImgPath="C:\\Users\\anubh\\Desktop\\DeskTop Icons\\Java Project Pics\\6.png";
        lbl_image4.setIcon(ResizeImage4(ImgPath,null));
        ImgPath="C:\\Users\\anubh\\Desktop\\DeskTop Icons\\Java Project Pics\\10.png";
        lbl_image5.setIcon(ResizeImage5(ImgPath,null));
    }
    int count=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_image3 = new javax.swing.JLabel();
        lbl_image4 = new javax.swing.JLabel();
        lbl_image5 = new javax.swing.JLabel();
        lbl_image2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setLocation(new java.awt.Point(540, 250));
        setMinimumSize(new java.awt.Dimension(870, 590));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Willing to donate something?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 352, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Or in need of something?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 130, 300, 29);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("DONATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(202, 220, 190, 217);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("GET DONATION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 220, 180, 217);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("ADMIN PANEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 480, 440, 66);
        getContentPane().add(lbl_image3);
        lbl_image3.setBounds(10, 220, 190, 210);
        getContentPane().add(lbl_image4);
        lbl_image4.setBounds(650, 220, 140, 210);

        lbl_image5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(lbl_image5);
        lbl_image5.setBounds(30, -30, 780, 260);
        getContentPane().add(lbl_image2);
        lbl_image2.setBounds(0, 0, 870, 570);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        close();
        DonateFinal df=new DonateFinal();
        df.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
        GetDonationFinal gd=new GetDonationFinal();
        gd.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminLoginFinal alf=new AdminLoginFinal();
        alf.setVisible(true);
        close();
        count++;
        if(count>=2){
            alf.close();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFinal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_image2;
    private javax.swing.JLabel lbl_image3;
    private javax.swing.JLabel lbl_image4;
    private javax.swing.JLabel lbl_image5;
    // End of variables declaration//GEN-END:variables
    public void close(){
        WindowEvent wc=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wc);
    }
}
